getwd()
setwd("~/Desktop/R_scripts/")
source("https://bioconductor.org/biocLite.R")
biocLite()
# if any package can't be installed, close Rstudio and run it as administrator
# also consider installing failed dependecny independently, before retriying instalation of main package
biocLite("GO.db")
biocLite("Hmisc") # dependancy for DESeq2
biocLite("DESeq2")
biocLite("foreach")
install.packages("gplots")
install.packages("ggrepel") 
biocLite("RColorBrewer")
biocLite("NMF")
biocLite("polysat")
biocLite("remotes")
biocLite("ballgown")
source("http://bioconductor.org/biocLite.R") 
biocLite("rhdf5") 
devtools::install_github("pachterlab/sleuth")
biocLite("gridExtra")
install.packages("devtools")
biocLite(devtools)
install_github("alyssafrazee/RSkittleBrewer")
install.packages("XML")
biocLite("reposTools")
install.packages2("genefilter")
biocLite("ASMap")
biocLite(parallel)
biocLite(rrBLUP)
biocLite(ballgown)
biocLite(RSkittleBrewer)
biocLite(genefilter)
biocLite(dplyr)
biocLite(cowplot)
biocLite(sleuth)
biocLite(MASS)
biocLite(shiny)
biocLite(polysat) # for the analysis of microsatellite data of any ploidy level
biocLite(dplyr)   # these two are very convenient for a number of data transformations
biocLite(ape)     # to build the NJ tree
biocLite(readxl)  # to read from Excel files
biocLite(RColorBrewer) # for nice colours
biocLite(stringi)
biocLite(stringr)
biocLite(ggplot2)
biocLite(dpylr)
biocLite("magrittr")
biocLite("ggrepel")
biocLite(RColorBrewer)
biocLite("readxl")
biocLite("magrittr")
biocLite("tidyr")
biocLite("forcats")
biocLite("multcomp")
biocLite(readxl)
biocLite('edgeR')

